# .travis.yml setup
sudo:
  - enabled
os:
  - linux
dist:
  - trusty
language:
  - python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

install:
  - pip install -e .

# run tests
script:
  - .travis_tests/tests.py
